name: dotnet package

on:
  push:
   branches:
      - main
      - develop/*
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./OTUS.Homework
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./OTUS.Homework
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: ./OTUS.Homework
